#!/usr/bin/env python

Import('env')

#env.Prepend(CPPPATH=[env["NINTENDO_SDK_ROOT"] + '/Include']) # because of new dev env

env.add_source_files(env.modules_sources, "*.cpp") # Add all cpp files to the build